<?php

$arr = [
    "Send from",
    "Home",
    "How it work",
    "Help",
    "Contact",
    "About Us",
    "Blog",
    "FAQ",
    "Sign In",
    "Sign Up",
    "My Profile",
    "Profile Settings",
    "About Company",
    "Useful Links",
    "All Right Reserved.",
    "Subscribe",
    "Transfer Log",
    "Payment History",
    "Transaction",
    "Payment Log",
    "Support",
    "Support Ticket",
    "2FA Security",
    "Logout",
    "You have no notifications",
    "Clear",
    "Payment Hold",
    "Amount",
    "Status",
    "Pending",
    "Rejected",
    "Completed",
    "Close",
    "Accept",
    "Reject",
    "Your Card Information",
    "Card Number",
    "Name On Your Card",
    "Payment Preview",
    "PLEASE SEND EXACTLY",
    "SCAN TO SEND",
    "Please Pay",
    "To Get",
    "Pay Now",
    "Pay via Monnify",
    "Pending Payment",
    "Complete Payment",
    "Rejected Payment",
    "Search",
    "Transaction ID",
    "Gateway",
    "Charge",
    "Time",
    "Detail",
    "Complete",
    "Cancel",
    "No Data Found!",
    "Transactions",
    "Admin Feedback",
    "Payment Information",
    "Request Amount",
    "Charge Amount",
    "Total Payable",
    "Confirm Now",
    "Image Update",
    "Profile Information",
    "Password Setting",
    "First Name",
    "Last Name",
    "Username",
    "Email Address",
    "Phone Number",
    "Language",
    "Preferred language",
    "Select Language",
    "Password",
    "Address",
    "Update User",
    "Current Password",
    "New Password",
    "Forget Password",
    "Confirm Password",
    "Update Password",
    "Reset Password",
    "Send Password Reset Link",
    "Don't have any account?",
    "Create Ticket",
    "Last Reply",
    "Action",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "Customer Reply",
    "Image Upload",
    "Upload File",
    "Reply",
    "Are you want to close ticket?",
    "Confirm",
    "All Payment",
    "Cancel Payment",
    "Search for Transaction ID",
    "Remark",
    "SL No.",
    "Two Factor Authenticator",
    "Deactive Two Factor",
    "Active Two Factor",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "DOWNLOAD APP",
    "Payment By",
    "Payable",
    "Email Verification",
    "Code",
    "Email Or Username",
    "Forgot password?",
    "Already have an account?",
    "Enter Code",
    "Didn't get Code? Click to",
    "Resend code",
    "Updated Successfully.",
    "Password Changes successfully.",
    "Current password did not match",
    "Two Factor has been enabled.",
    "Two Factor has been disabled.",
    "Wrong Verification Code.",
    "Image could not be uploaded.",
    "Invalid Request!",
    "Payment has been released.",
    "Your report has been sent.",
    "Email verification code has been sent",
    "SMS verification code has been sent",
    "Sending Failed",
    "Email verification code is required",
    "Verification code didn't match!",
    "Wrong Verification Code",
    "Blog Details",
    "Contact Us",
    "Your Name",
    "Your Email",
    "Your Subject",
    "Message",
    "Send Message",
    "Forbidden",
    "You don't have permission to access ‘/’ on this server",
    "Back To Home",
    "Opps!",
    "The page you are looking for was not found.",
    "Method Not Allowed",
    "Sorry, your session has expired",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "Previous",
    "Next",
    "Download On",
    "App Store",
    "Google Play",
    "Continue",
    "Add Recipient",
    "Recipient Name",
    "Recipient Contact No.",
    "Recipient Email Address",
    "Source Of Fund",
    "Sending Purpose",
    "Select One",
    "Fees",
    "Exchange rate",
    "You pay in total",
    "Your recipient gets",
    "Get a promo code?",
    "Apply",
    "Invalid promo code",
    "Select Country",
    "SEND",
    "RECEIVE",
    "SL",
    "Invoice",
    "Recipient",
    "Send Amount",
    "Send At",
    "Receive At",
    "Rate",
    "Information Need",
    "Cancelled",
    "Processing",
    "Fill Up Form",
    "Pay Payment",
    "Details",
    "Payment Failed",
    "READ MORE",
    "By Admin",
    "Fee Depend on your service",
    "Remove",
    "Change",
    "Select",
    "Joined At",
    "Subject",
    "Provider must be required",
    "Receiver Country Not Found",
    "Receiver Country Service Not Available",
    "Sender country is required",
    "Please select a currency to receive",
    "Service is required",
    "Enter Amount",
    "Sender Country Not Found",
    "You are not eligible to change request.",
    "RECIPIENT DETAILS",
    "TRANSFER LOG",
    "Invalid Payment Request",
    "Payment has been completed",
    "Payment has been rejected",
    "Wait for payment approval by admin",
    "Only png, jpg, jpeg images are allowed",
    "First Name field is required",
    "Last Name field is required",
    "Mail has been sent",
    "Subscribe successfully",
    "The email field is required."
];

return $arr;



